---
spring:
  config.activate.on-profile: default
  datasource:
    url: "jdbc:sqlite:..\\db.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always
  web.resources.static-locations: "file:..\\app"

cds:
  odata-v4.endpoint.path: "/api"
  data-source:
      auto-config.enabled: true
  security:
    mock:
      users:
        - name: admin
          password: admin
          role: admin
        - name: user
          password: user

server:
  port: 8080
